services:
  db:
  #MariaDBコンテナ
    image: mariadb:10.7
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: testdb
      MARIADB_USER: testuser
      MARIADB_PASSWORD: testpass
    volumes:
      - db-data:/var/lib/mysql
  phpadmin:
    image: phpmyadmin:5.2
    depends_on:
      - db
    environment:
    #データベースのホスト名
      PMA_HOST: db
      #データベースのユーザー名
      PMA_USER: testuser
      #データベースのパスワード
      PMA_PASSWORD: testpass
    ports:
      - "8080:80"
    volumes:
    #ボリューム
      - phpmyadmin-data:/sessions
volumes:
  db-data:
  phpmyadmin-data: