services:
  db:
    image: mariadb:10.7
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
  web:
  #dockerファイルを基にするのでbuild パス名
    build: .
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - ./src:/samplerails
volumes:
  db-data:
